#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2010 Holoscópio Tecnologia
# Author: Luciana Fujii Pontello <luciana@holoscopio.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import sys
sys.path.append("/usr/local/lib")

import gobject
import gtk
import os

try:
    FLUMOTION_PATH = '/usr/lib/flumotion/python/'
    path = os.path.join(sys.argv[len(sys.argv)-1], 'flumotion')
    if len(sys.argv) > 1:
        if not os.path.exists(path):
            print 'Error: Path', sys.argv[len(sys.argv)-1], ' is not a valid path of flumotion.'
        else:
            FLUMOTION_PATH = sys.argv[len(sys.argv)-1]
    sys.path.insert(0, FLUMOTION_PATH)
    #print 'FLUMOTION_PATH', FLUMOTION_PATH
    from twisted.internet import gtk2reactor
    gtk2reactor.install()
    from twisted.internet import reactor
except:
    pass

import sltv.ui

def main():
    sltv.ui.SltvUI()
    gobject.threads_init()
    gtk.gdk.threads_init()
    
    try:
        reactor.run()
    except:
        gtk.main()

if __name__ == '__main__':
    main()

